@startuml "Business Case: HAMPI (Final con 3 Notas)"
left to right direction
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor #333333
skinparam titleFontSize 18
skinparam defaultFontName Arial

skinparam noteBackgroundColor #FEFECE
skinparam noteBorderColor #A80036

skinparam usecase {
  BackgroundColor #C7F4FF
  BorderColor #7A1631
  StereotypeFontColor #2E7D32
}
skinparam actor {
  BackgroundColor #C7F4FF
  BorderColor #7A1631
  StereotypeFontColor #2E7D32
}
skinparam Arrow {
  Color #7A1631
}

actor/ "Paciente" as Paciente
actor/ "Médico" as Medico
actor/ "Cuidador" as Cuidador

usecase/ "Gestionar Tratamiento\nMédico" as BUC1
usecase/ "Supervisar Pacientes" as BUC2
usecase/ "Dar Soporte\na Paciente" as BUC3

Paciente --> BUC1
Medico --> BUC2
Cuidador --> BUC3

note right of BUC1
  El paciente
  registra recordatorios, adherencia
  y sus indicadores de salud.
end note
 
note right of BUC2
  El médico visualiza el historial
  y progreso para tomar decisiones
  clínicas y ajustar el tratamiento.
end note

note right of BUC3
  El cuidador accede a la información
  compartida para brindar soporte
  emocional y seguimiento.
end note

BUC2 ..> BUC1 : <<obtiene datos de>>
BUC3 ..> BUC1 : <<obtiene datos de>>

@enduml